CREATE TABLE BOOK(
	ISBN VARCHAR2(20) PRIMARY KEY,
	CATEGORY NUMBER(1)NOT NULL,
	BNAME VARCHAR2(128)NOT NULL,
	WRITER VARCHAR2(30)NOT NULL,
	PRENT NUMBER(38)NOT NULL,
	ORIGINPRICE NUMBER(20) NOT NULL,
	SUMMARY VARCHAR2(1800)NOT NULL
);
 

CREATE TABLE HISTORY(
 	ID VARCHAR2(20) PRIMARY KEY,
 	ISBN VARCHAR2(20) NOT NULL,
 	bname VARCHAR2(128) NOT NULL,
    WRITER VARCHAR2(30)NOT NULL
);

CREATE TABLE MEMBER(
 	ID VARCHAR2(20) PRIMARY KEY,
 	PWD VARCHAR2(16) NOT NULL,
 	NAME VARCHAR2(20) NOT NULL,
 	EMAIL VARCHAR2(30) NOT NULL,
 	INTERESTCATEGORY NUMBER(1) NOT NULL,--ISBN 부가 기호표에 따른 내용 대분류 기준, 관심 분야
 	POINT INT NOT NULL,
 	CASH INT NOT NULL
);


CREATE TABLE QUIZ(
	QUIZID  NUMBER(13) PRIMARY KEY,
    ISBN VARCHAR2(20) not null,
    CONSTRAINT fk_ISBN FOREIGN key(isbn) REFERENCES BOOK(ISBN),
	QUESTION VARCHAR2(300) NOT NULL,
	ANSWER NUMBER(1) NOT NULL,
);
 
CREATE SEQUENCE QUIZID  --시퀀스
	INCREMENT BY 1 --증감숫자 1
	START WITH 1 --시작숫자 1
	MINVALUE 1 --최소값 1
	MAXVALUE 1000 --최대값 1000
	NOCYCLE --순한하지않음
; 


 
 
