CREATE TABLE BOOK(
	ISBN NUMBER(13) PRIMARY KEY,
	GENRE VARCHAR2(30),
	B_NAME VARCHAR2(128),
	WRITER VARCHAR2(30),
	P_RENT NUMBER(38),
	CLEAR_NUM NUMBER(38),
	ORIGIN_PRICE NUMBER(20),
	SUMMARY VARCHAR2(1800)
);
 
CREATE TABLE HISTORY(
 	ID VARCHAR2(20) PRIMARY KEY,
 	ISBN NUMBER(13),
 	PRICE INT,
 	CLEAR INT
);
 
CREATE TABLE MEMBER(
 	ID VARCHAR2(20) PRIMARY KEY,
 	PASS VARCHAR2(20),
 	ENAME VARCHAR2(20),
 	EMAIL VARCHAR2(20),
 	GENRE VARCHAR2(20),
 	GRADE NUMBER(1),--1 : VVIP,2 : VIP, 3 : normal
 	POINT INT,
 	CASH INT
);

CREATE TABLE QUIZ(
	QUIZID  NUMBER(13) PRIMARY KEY,
    ISBN NUMBER(13) not null,
    CONSTRAINT fk_ISBN FOREIGN key(isbn) REFERENCES BOOK(ISBN),
	QUESTION VARCHAR2(300),
	ANSWER NUMBER(1),
    QUIZUPDATE DATE
);
 
CREATE SEQUENCE QUIZID  --시퀀스
	INCREMENT BY 1 --증감숫자 1
	START WITH 1 --시작숫자 1
	MINVALUE 1 --최소값 1
	MAXVALUE 1000 --최대값 1000
	NOCYCLE --순한하지않음
; 


 
 