CREATE TABLE MEMBER(
 	ID VARCHAR2(20) PRIMARY KEY,
 	PWD VARCHAR2(16) NOT NULL,
 	NAME NVARCHAR2(20) NOT NULL,
 	EMAIL VARCHAR2(30) CONSTRAINT UK_EMAIL UNIQUE NOT NULL,
 	INTEREST_CATEGORY NUMBER(1) NOT NULL,
 	CASH NUMBER(10) NOT NULL
);


CREATE TABLE BOOK(
    BOOK_ID NUMBER(10) PRIMARY KEY,
	ISBN VARCHAR2(30) NOT NULL,
	CATEGORY NUMBER(1)NOT NULL,
	BNAME VARCHAR2(128)NOT NULL,
	WRITER VARCHAR2(40)NOT NULL,
	PRICE NUMBER(10) NOT NULL,
	SUMMARY VARCHAR2(1800)NOT NULL,
	IMAGE BLOB,
	REGISTER_ID VARCHAR2(20) NOT NULL,
	CONSTRAINT fk_REGISTER_ID FOREIGN key(REGISTER_ID) REFERENCES MEMBER(ID),
	LEND_ID VARCHAR2(20) NOT NULL,
	CONSTRAINT fk_LEND_ID FOREIGN key(LEND_ID) REFERENCES MEMBER(ID),
    ORDER BY  B_NAME
);


CREATE TABLE ADMIN(
	ID VARCHAR2(20) PRIMARY KEY,
 	PWD VARCHAR2(16) NOT NULL
);


 
